### PR TITLE
V1.0.2 Bugs corrections and optimizations and news properties + trad

### PR DESCRIPTION
**Pull request by jimibi**
it works best like that

### CODE REVIEW

**Comment by RedMarlin** [comment]
Wow, thanks for great work!
I will revise the proposed changes and merge accordingly in the next few days.

**Comment by jimibi** [comment]
Thanks

**Comment by RedMarlin** [comment]
I have analyzed the pull request. The localization is great and I will adapt all the changes there also thanks for adding license.
As for moving css and js to remote source I wont implement this as I prefer other approach of having all the resources on the same server without need to rely on 3rd party as you have more control over how it will be served.

The width and height of the map defined in partial is a neat feature but this can cause backward compatibility problems for people already using this module and besides it kills the flexibility of setting this in CSS (ie setting the size through media queries). 

Again, thanks for the contribution and hard work! Im not implementing some features you added not because they are wrong/badly written, but because I prefer other approach. I hope you will understand :)

**Comment by jimibi** [comment]
I also like your approach and and it's better for media queries and compatibility.
If I have more ideas I would not hesitate to make a commits with you approach.
Thanks

**Pull request merged**
